### ISSUE TITLE
Network files 

### ISSUE THREAD

**Issue by balola** [MichalBures/obsidian-file-path-to-uri#2]
Hi Michal,

Could you implement the network file insert method too:

(file:///%5C%5C + "Copy as path" (Shift+right click on the file)

I use it as:
Copy as path (by hand)
Change \ to /
Change " " to %20
And insert it in my template as below:
```Doc: [📄](file:///%5C%5CAndHereComesTheConvertedPath)```

Your method would be nicer!! :)

Thanks

Fules

**Comment by MichalBures** [comment]
Hi,

I've added support for the network paths as you asked. I also added feature that strips the surrounding " from the selected text. So that means that now you can easily paste the "Copy as path" path, select the whole thing and convert it to a file link.

Here's the updated version if you could please test it before I release a new version? Download this file [main.txt](https://github.com/MichalBures/obsidian-file-path-to-uri/files/5896139/main.txt), rename it to .js and copy it to the plugin folder `path-to-your-vault\.obsidian\plugins\obsidian-file-path-to-uri\main.js` and restart Obsidian.

**Comment by balola** [comment]
Hi,

Thank's in advance. I am going to try it at home. I forgot to mention to leave the surrounding " , thanks, as also the **two \\ in front of the path**. I put the two %5C code in my sample, so it is also nesseceary to change these caracters. Otherwise it will be a really helpfull plugin, I have suggested it as a problem solving method in a comment yet.
Füles

**Comment by balola** [comment]
Hi Michal,

I tried, the result is:

```
file://%22//path.xlsx%22

what we need

file:///%5C%5Cpath.xlsx
```

So what we need:
file:/// instead of file//%22
%5C%5C instead of //, how i see \\ what our system uses
xlsx instead of xlsx%22 at the end of the row

Thank's
Füles

**Comment by balola** [comment]
Hi,
I have just find this convesation in the Community:

The only problem is the %20 character 
Answere:
Yes - enclose your file path in "<...>
For example:
jpg: [description](<file:///D:\downloads\file name with spaces.jpg>)

Yes, it works.
Füles

**Comment by MichalBures** [comment]
I've just released a new version which supports network locations.

**Comment by balola** [comment]
That is great.
Thanks.
Füles
