### ISSUE TITLE
Option for relative paths

### ISSUE THREAD

**Issue by AMGMNPLK** [MichalBures/obsidian-file-path-to-uri#6]
Would be great to have the option to choose a relative path.

**Comment by MichalBures** [comment]
Relative to what? To your vault? If you have you vault on `C:\vault` and link file `C:\file.txt` as relative path you'll get something like `..\file.txt`. This new relative path is now only usable if you use some kind of custom click handler. And since Obsidian is using the system one afaik that means it won't work cause it's not a valid path.
